# Generated by Django 3.0.4 on 2020-11-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0015_article_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslusgi',
            name='image',
            field=models.ImageField(blank='null', default='images/no_photo/no_photo.png', null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
