# Generated by Django 3.0.4 on 2020-11-08 14:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0016_auto_20201108_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
    ]
