# Generated by Django 3.0.4 on 2021-07-04 07:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0017_auto_20201108_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='basic',
            field=models.BooleanField(default='0', verbose_name='Основной'),
        ),
        migrations.AddField(
            model_name='category',
            name='immutable',
            field=models.BooleanField(default='0', verbose_name='Неизменяемый'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.BooleanField(verbose_name='Опубликованный'),
        ),
        migrations.AlterField(
            model_name='uslusgi',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uslugi.Region', verbose_name='Регион'),
        ),
    ]
