# Generated by Django 3.0.4 on 2021-07-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0018_auto_20210704_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='moskva', max_length=70, verbose_name='url'),
            preserve_default=False,
        ),
    ]
