# Generated by Django 3.2.5 on 2021-07-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0019_region_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslusgi',
            name='basic',
            field=models.BooleanField(default='0', verbose_name='Основной'),
        ),
    ]
